---
stages:
  - update
  - lint
  - test
  - lsif
  - deploy

include:
  - local: .gitlab/ci/lint/eslint.gitlab-ci.yml
  - local: .gitlab/ci/lint/prettier.gitlab-ci.yml
  - local: .gitlab/ci/lint/shellcheck.gitlab-ci.yml
  - local: .gitlab/ci/lint/yamllint.gitlab-ci.yml
  - local: .gitlab/ci/lsif/go.gitlab-ci.yml
  - local: .gitlab/ci/update/project.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
